# Generated by Django 2.2.7 on 2019-11-17 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=100)),
                ('iso_639_1_code', models.CharField(max_length=7)),
                ('iso_639_2_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('is_word', models.BooleanField(default=True)),
                ('number_of_syllables', models.IntegerField()),
                ('english_transcription_system', models.CharField(max_length=250)),
                ('transcription', models.TextField()),
                ('international_phonetic_alphabet', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='connections.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonetic_relationship', models.BooleanField()),
                ('semantic_relationship', models.BooleanField()),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='connections.Word')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='connections.Word')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='connections.Profile')),
            ],
        ),
    ]
