# Generated by Django 2.2.7 on 2019-11-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='iso_693_3_code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='iso_693_3_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='iso_639_1_code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='iso_639_2_code',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
