# Generated by Django 2.2.7 on 2019-11-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('traditional', models.TextField(blank=True, null=True)),
                ('simplified', models.TextField(blank=True, null=True)),
                ('pinyin', models.TextField(blank=True, null=True)),
                ('english', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entries',
                'managed': False,
            },
        ),
    ]
